import Link from "next/link";
import {PageHero,ServiceIcon,Shell} from "../site";

const items=[
  {n:"01",title:"Mecanografía y transcripción",paragraphs:["Convierte textos manuscritos, hojas impresas, cartas, notas y borradores en documentos digitales claros y ordenados. El contenido puede prepararse para conservar, editar, compartir por correo o imprimir.","Se presta atención especial a nombres, números, fechas y palabras difíciles de leer. Cuando algo no está claro, se consulta al cliente o se señala la duda en lugar de inventar información."],points:["Manuscritos y notas","Cartas y documentos personales","Informes y trabajos académicos","Archivos editables o para imprimir"]},
  {n:"02",title:"Preparación de documentos",paragraphs:["Ayuda a convertir información suelta en un documento con estructura y presentación adecuada. Puede incluir la organización de títulos, párrafos, tablas, listados, campos y secciones según el uso final.","Este servicio resulta útil para currículos, solicitudes, comunicaciones, modelos administrativos y documentos personales. Si existe una plantilla institucional o un ejemplo, conviene entregarlo desde el comienzo."],points:["Currículos y solicitudes","Cartas y comunicaciones","Listados y registros","Documentos con modelo específico"]},
  {n:"03",title:"Formato y revisión básica",paragraphs:["Mejora el orden visual de documentos mediante márgenes, espaciado, alineación, jerarquías, numeración y paginación. También pueden detectarse inconsistencias evidentes antes de imprimir o entregar.","La revisión básica ayuda con la presentación y legibilidad, pero no sustituye una corrección profesional de estilo, una revisión académica especializada ni asesoría legal. El cliente debe confirmar los datos y el contenido final."],points:["Márgenes y espaciado","Títulos y jerarquías","Paginación y orden","Preparación para impresión"]},
  {n:"04",title:"Formularios y trámites",paragraphs:["Osmany ayuda a organizar la información y completar formularios generales, migratorios y de ciudadanía española, incluida la Ley de Memoria Democrática. También ofrece orientación para solicitudes de visa de turismo a México según el alcance acordado.","El cliente debe aportar datos verdaderos, vigentes y los documentos requeridos por la autoridad correspondiente. La preparación documental no constituye representación legal ni garantiza la aprobación de visas, ciudadanía u otros trámites."],points:["Formularios generales","Visa de turismo a México","Ciudadanía española y LMD","Organización de datos y documentos"],href:"/otros-servicios",link:"Conocer formularios y otros servicios →"},
  {n:"05",title:"Impresión, copias y terminaciones",paragraphs:["Impresión moderna a color o en blanco y negro para documentos personales, profesionales y académicos. También se realizan fotocopias, impresión de tesis y trabajos extensos, según la cantidad y el acabado solicitado.","Puede coordinarse encuadernación y plastificado de carnés, identificaciones o documentos hasta tamaño Carta. Antes de producir el trabajo se confirman páginas, ejemplares, color, materiales y fecha de entrega."],points:["Color y blanco y negro","Fotocopias y tesis","Encuadernación","Plastificado hasta tamaño Carta"],href:"/impresion",link:"Conocer impresión y copias →"},
  {n:"06",title:"Digitalización y modelos de oficina",paragraphs:["Convierte documentos físicos en archivos digitales para conservar, enviar, organizar o volver a imprimir. Las páginas pueden reunirse y ordenarse para facilitar su consulta y almacenamiento.","También se diseñan modelos reutilizables para oficinas y pequeños negocios, como registros, controles, recibos, listados y formularios internos adaptados a la información que necesita cada cliente."],points:["Escaneo y archivo digital","Documentos de varias páginas","Registros y controles","Plantillas reutilizables"],href:"/otros-servicios",link:"Ver digitalización y modelos →"}
];

export default function Servicios(){return <Shell>
  <PageHero kicker="Servicios" title="Cada palabra, en su lugar."><p>Soluciones para preparar, conservar, imprimir y presentar sus documentos. Cada encargo se revisa personalmente antes de confirmar alcance, plazo y tarifa.</p></PageHero>
  <figure className="promo-page-image wrap"><img src="/osmany-servicios-promo.png" alt="Servicios profesionales de mecanografía de Osmany Santos Macías"/></figure>
  <section className="section wrap main-services"><div className="section-head"><div><span className="kicker">Qué puede solicitar</span><h2>Servicios explicados para elegir mejor.</h2></div><p>No tiene que conocer el nombre exacto del servicio. Explique qué material tiene y qué resultado necesita; Osmany le orientará sobre la opción adecuada.</p></div><div className="detail-list">{items.map(item=><article key={item.n}><ServiceIcon n={item.n}/><div><h2>{item.title}</h2>{item.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<ul>{item.points.map(point=><li key={point}>{point}</li>)}</ul>{item.href&&<Link className="text-link" href={item.href}>{item.link}</Link>}</div></article>)}</div></section>
  <section className="services-choice"><div className="wrap"><div className="section-head"><div><span className="kicker light">¿Por dónde empezar?</span><h2>Cuente qué desea resolver.</h2></div><p>Una breve descripción y una muestra del material suelen ser suficientes para identificar el servicio y preparar una cotización.</p></div><div className="info-card-grid dark-grid"><article><h3>Tengo un texto en papel</h3><p>Indique si está manuscrito o impreso, cuántas páginas tiene y si desea recibirlo como archivo digital, impresión o ambos.</p></article><article><h3>Tengo un archivo digital</h3><p>Explique si necesita organizarlo, darle formato, imprimirlo, producir copias o añadir encuadernación y plastificado.</p></article><article><h3>Tengo un trámite</h3><p>Diga qué formulario debe completar, ante qué institución será presentado y qué documentación o instrucciones ha recibido.</p></article></div></div></section>
  <section className="section wrap services-request"><div className="section-head"><div><span className="kicker">Para recibir una respuesta precisa</span><h2>Información útil para cotizar.</h2></div><p>Puede enviarla por teléfono o correo junto con una fotografía o muestra del material.</p></div><div className="faq-grid"><article><h3>Material y cantidad</h3><p>Describa el original e indique páginas, documentos, formularios, fotografías o ejemplares aproximados.</p></article><article><h3>Resultado deseado</h3><p>Explique si necesita archivo editable, PDF, impresión, copias, plastificado, encuadernación u otra terminación.</p></article><article><h3>Fecha de entrega</h3><p>Comunique cuándo lo necesita y si existe una fecha oficial de presentación o entrega académica.</p></article><article><h3>Modelo o requisitos</h3><p>Comparta plantillas, ejemplos o instrucciones de la institución para preparar el documento correctamente.</p></article></div><div className="services-links"><Link className="button primary" href="/proceso">Ver cómo trabajo →</Link><Link className="button primary" href="/tarifas">Consultar cómo se cotiza →</Link></div></section>
  <section className="mini-cta"><div className="wrap"><h2>¿Tiene un encargo diferente?</h2><p>Explíquelo, envíe una muestra y reciba una respuesta directa antes de comenzar.</p><Link className="button cream" href="/contacto">Hacer una consulta →</Link></div></section>
</Shell>}
