import Link from "next/link";
import {PageHero,Shell} from "../site";

const factors=[
  ["01","Tipo de servicio","El cálculo comienza por el servicio que necesita: mecanografía, impresión, fotocopiado, digitalización, plastificado, encuadernación, restauración de fotografías, diseño de modelos de oficina o llenado de formularios."],
  ["02","Cantidad y extensión","Se tiene en cuenta el número de páginas, copias, documentos, fotografías o formularios. En trabajos grandes, también se revisa si todas las piezas requieren el mismo proceso o diferentes terminaciones."],
  ["03","Estado y complejidad","Un original claro y ordenado requiere un tratamiento distinto a un manuscrito difícil de leer, una fotografía deteriorada o un documento que necesita correcciones, formato y organización especial."],
  ["04","Materiales y acabado","El tamaño y tipo de papel, la impresión a color o en blanco y negro, el plastificado, la encuadernación y otras terminaciones forman parte de la cotización."],
  ["05","Plazo de entrega","La fecha requerida se acuerda antes de comenzar. Los encargos urgentes dependen de la carga de trabajo, la disponibilidad de materiales y el tiempo necesario para entregar un resultado cuidadoso."]
];

const quoteDetails=[
  ["Servicio","Explique qué necesita hacer y cuál será el uso final del documento."],
  ["Cantidad","Indique páginas, copias, fotografías, formularios o ejemplares aproximados."],
  ["Original","Diga si entrega archivos digitales, hojas impresas, manuscritos o fotografías físicas."],
  ["Resultado","Señale el formato, tamaño, color, acabado o tipo de archivo que desea recibir."],
  ["Fecha","Comunique para cuándo lo necesita y si existe alguna fecha de trámite o entrega."]
];

export default function Tarifas(){return <Shell>
  <PageHero kicker="Tarifas" title="Cada encargo recibe su propia cotización."><p>El precio depende del trabajo real que requiera su solicitud. Explique su necesidad y Osmany confirmará el alcance, el plazo y el importe antes de comenzar.</p></PageHero>

  <section className="tariff-images wrap"><figure><img src="/document-workspace.jpg" alt="Preparación digital de documentos en un espacio moderno"/><figcaption>Preparación, organización y formato digital</figcaption></figure><figure><img src="/modern-printing.jpg" alt="Impresión de documentos con equipo multifunción"/><figcaption>Impresión, copias y terminación</figcaption></figure></section>

  <section className="section wrap"><div className="section-head"><div><span className="kicker">Cómo se calcula</span><h2>Una tarifa justa según el trabajo.</h2></div><p>No se aplica una cifra única a necesidades diferentes. La cotización considera el tiempo, los materiales, la dificultad y el resultado solicitado.</p></div><div className="detail-list">{factors.map(f=><article key={f[0]}><span className="kicker">{f[0]}</span><div><h2>{f[1]}</h2><p>{f[2]}</p></div></article>)}</div></section>

  <section className="tariff-request"><div className="wrap"><div className="section-head"><div><span className="kicker light">Para cotizar mejor</span><h2>¿Qué información debe enviar?</h2></div><p>Puede escribir por teléfono o correo. Si es posible, adjunte una fotografía o muestra legible del material para valorar mejor el trabajo.</p></div><div className="quote-detail-grid">{quoteDetails.map((item,index)=><article key={item[0]}><span>0{index+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div></div></section>

  <section className="section wrap tariff-examples"><div className="section-head"><div><span className="kicker">Ejemplos de cotización</span><h2>¿Qué puede cambiar el precio?</h2></div><p>Estos ejemplos ayudan a comprender por qué primero se revisa cada solicitud. No representan precios fijos.</p></div><div className="info-card-grid"><article><h3>Mecanografía</h3><p>Se considera la cantidad de páginas, la claridad del manuscrito y el formato solicitado. Un texto limpio requiere menos tiempo que hojas con tachaduras, notas al margen, tablas o letra difícil de interpretar.</p></article><article><h3>Impresión y copias</h3><p>Influyen el número de páginas y ejemplares, el tamaño del papel y si se imprime a color o en blanco y negro. La encuadernación y otras terminaciones se cotizan según los materiales.</p></article><article><h3>Plastificado</h3><p>La tarifa depende del tamaño y la cantidad de documentos, hasta tamaño Carta. Antes de plastificar se confirma que el contenido esté correcto, porque el acabado está pensado para ser permanente.</p></article><article><h3>Digitalización</h3><p>Se valora la cantidad de páginas, el estado de los originales y si deben organizarse, nombrarse o reunirse en archivos de varias páginas.</p></article><article><h3>Formularios</h3><p>Un formulario sencillo no requiere el mismo tiempo que un trámite con múltiples secciones y documentos de apoyo. La cotización cubre la preparación acordada, no tasas oficiales ni decisiones de autoridades.</p></article><article><h3>Fotografías y restauración</h3><p>El trabajo depende del deterioro, la resolución y el resultado deseado. El retoque, la colorización y la impresión son procesos diferentes y se confirman por separado.</p></article></div></section>

  <section className="section wrap tariff-process"><div className="section-head"><div><span className="kicker">Confirmación</span><h2>Todo claro antes de empezar.</h2></div><p>La solicitud se revisa primero para evitar sorpresas y definir exactamente qué recibirá.</p></div><ol><li><b>1. Revisión</b><p>Osmany examina la información y, cuando sea necesario, el estado de los originales.</p></li><li><b>2. Acuerdo</b><p>Se confirma el servicio, la cantidad, la terminación, el tiempo estimado y el precio.</p></li><li><b>3. Realización</b><p>El trabajo comienza después de que usted apruebe las condiciones acordadas.</p></li></ol><p className="tariff-note"><strong>Importante:</strong> los trámites migratorios y de ciudadanía pueden requerir documentos adicionales. La asesoría ayuda a preparar y llenar formularios, pero no garantiza decisiones de consulados, registros u otras autoridades.</p></section>

  <section className="payment-options"><div className="wrap"><div><span className="kicker light">Formas de pago</span><h2>Usted elige la opción más conveniente.</h2><p>El servicio puede pagarse en pesos cubanos o dólares estadounidenses. También pueden acordarse transferencias en CUP, MLC o USD a tarjeta, así como pagos mediante Zelle.</p><p>La moneda, el método de pago y el importe final se confirman directamente con Osmany antes de comenzar. Cuando corresponda una conversión, se informa y acuerda previamente para que ambas partes tengan claridad.</p></div><aside><b>Opciones disponibles</b><span>Efectivo en CUP</span><span>Efectivo en USD</span><span>Transferencia en CUP</span><span>Transferencia en MLC o USD</span><span>Zelle</span><small>La disponibilidad de cada opción se confirma al solicitar la cotización.</small></aside></div></section>

  <section className="section wrap tariff-questions"><div className="section-head"><div><span className="kicker">Preguntas frecuentes</span><h2>Antes de confirmar.</h2></div><p>Una conversación breve suele ser suficiente para aclarar el encargo.</p></div><div className="faq-grid"><article><h3>¿Puedo preguntar sin compromiso?</h3><p>Sí. Puede explicar su necesidad y recibir información sobre alcance, disponibilidad y precio antes de decidir.</p></article><article><h3>¿Se aceptan trabajos urgentes?</h3><p>Depende del tamaño del encargo, los materiales y la carga de trabajo. Comunique la fecha exacta para confirmar si es posible.</p></article><article><h3>¿Puede cambiar la cotización?</h3><p>Solo si cambia el alcance acordado, por ejemplo, si se añaden páginas, copias, correcciones o terminaciones. Cualquier ajuste se conversa antes de continuar.</p></article><article><h3>¿Los materiales están incluidos?</h3><p>La cotización indicará lo incluido. Papel, plastificado, encuadernación u otros materiales se consideran según el acabado solicitado.</p></article></div></section>

  <section className="city-quote"><div className="wrap"><blockquote>Explique su necesidad. Recibirá una respuesta clara antes de comenzar.</blockquote><p>Cotización previa · Atención personal · Sin compromiso</p></div></section>
  <section className="mini-cta"><div className="wrap"><h2>Solicite una cotización.</h2><p>Indique el servicio, la cantidad, el estado del original y la fecha en que lo necesita.</p><Link className="button cream" href="/contacto">Escribir a Osmany →</Link></div></section>
</Shell>}
