import Link from "next/link";
import {BusinessCard,Footer,Header,ServiceIcon} from "./site";

export default function Home(){return <main><Header/>
  <section className="hero wrap">
    <div><div className="eyebrow">Mecanografía profesional · Cienfuegos</div><h1>Sus documentos,<br/><em>bien hechos.</em></h1><p className="lead">Precisión, claridad y atención personal para convertir manuscritos, formularios y textos en documentos limpios, ordenados y listos para entregar.</p><div className="actions"><a className="button primary" href="mailto:osmcfg1966@gmail.com">Solicitar un trabajo →</a><Link className="button text" href="/servicios">Ver servicios</Link></div></div>
    <div className="hero-card"><img src="/og.png" alt="Tarjeta gráfica de Osmany Santos Macías, mecanografía profesional en Cienfuegos"/></div>
  </section>
  <div className="trust"><div className="wrap"><span>Cienfuegos</span><i>◆</i><span>Atención personal</span><i>◆</i><span>Máquina + computadora</span></div></div>
  <section className="visual-proof wrap"><figure><img src="/typewriter-workspace.jpg" alt="Máquina de escribir en una mesa de trabajo moderna"/><figcaption>El cuidado de un oficio que combina tradición y herramientas actuales.</figcaption></figure><div><span className="kicker">Contacto profesional</span><h2>Guarde la tarjeta de Osmany.</h2><p>Úsela para solicitar su próximo documento, consultar disponibilidad o compartir el servicio con quien lo necesite.</p><BusinessCard/><Link className="arrow-link" href="/tarjeta">Ver todos los datos de contacto →</Link></div></section>
  <section className="section wrap"><div className="section-head"><div><span className="kicker">Lo esencial</span><h2>Oficio tradicional,<br/>soluciones actuales.</h2></div><p>Desde una página hasta un expediente completo: lectura atenta, formato consistente y presentación profesional.</p></div><div className="service-grid"><article className="service featured"><ServiceIcon n="01"/><h3>Mecanografía</h3><p>Textos manuscritos o impresos, en máquina y computadora.</p><Link href="/servicios">Conocer el servicio →</Link></article><article className="service"><ServiceIcon n="02"/><h3>Documentos</h3><p>Cartas, currículos, formularios y escritos claros.</p><Link href="/servicios">Ver posibilidades →</Link></article><article className="service"><ServiceIcon n="03"/><h3>Edición</h3><p>Organización visual y revisión básica de consistencia.</p><Link href="/servicios">Ver detalles →</Link></article></div><p className="disclaimer">Servicios y plazos se confirman directamente.</p></section>
  <section className="work-gallery wrap"><div className="gallery-heading"><span className="kicker">Del original a la entrega</span><h2>Cada documento tiene su recorrido.</h2><p>Del papel manuscrito al archivo organizado, y del archivo a una impresión lista para presentar.</p></div><div className="gallery-grid"><Link className="gallery-card handwritten" href="/proceso"><img src="/writing-desk.jpg" alt="Pluma estilográfica escribiendo sobre una hoja de papel"/><span><b>01</b><strong>El material original</strong><small>Notas, manuscritos y referencias</small></span></Link><Link className="gallery-card digital" href="/servicios"><img src="/document-workspace.jpg" alt="Espacio de trabajo digital moderno con computadora"/><span><b>02</b><strong>Preparación digital</strong><small>Orden, formato y claridad</small></span></Link><Link className="gallery-card printed" href="/impresion"><img src="/modern-printing.jpg" alt="Documentos preparados en una impresora multifunción moderna"/><span><b>03</b><strong>Impresión y acabado</strong><small>Color, copias, tesis y plastificado</small></span></Link></div><p className="photo-credit">Fotografías de archivo: <a href="https://unsplash.com/" target="_blank" rel="noreferrer">Unsplash</a> y <a href="https://www.pexels.com/photo/woman-preparing-paper-for-printing-photos-7014408/" target="_blank" rel="noreferrer">Pexels</a>.</p></section>
  <section className="process"><div className="wrap process-inner"><div><span className="kicker light">Cómo funciona</span><h2>Simple de principio a fin.</h2></div><ol><li><span>1</span><div><b>Cuente qué necesita</b><p>Envíe o lleve el texto.</p></div></li><li><span>2</span><div><b>Confirme el encargo</b><p>Se acuerdan formato y entrega.</p></div></li><li><span>3</span><div><b>Reciba su documento</b><p>Ordenado, legible y preparado.</p></div></li></ol></div></section>
  <section className="card-section wrap"><div><span className="kicker">Información directa</span><h2>Todo lo necesario para comenzar.</h2><p>Teléfono, correo y dirección reunidos en un solo lugar.</p><Link className="button dark" href="/contacto">Contactar a Osmany</Link></div><BusinessCard/></section>
  <section className="cta"><div className="wrap"><span className="kicker light">¿Tiene un documento pendiente?</span><h2>Vamos a ponerlo en limpio.</h2><a className="button cream" href="mailto:osmcfg1966@gmail.com">Escribir a Osmany →</a></div></section><Footer/>
</main>}
