import Link from "next/link";
import {PageHero,ServiceIcon,Shell} from "../site";

export default function Impresion(){return <Shell>
  <PageHero kicker="Impresión y copias" title="Del archivo al papel, bien presentado."><p>Impresión moderna a color o en blanco y negro, fotocopias, encuadernación y terminaciones para documentos personales, académicos y profesionales.</p></PageHero>
  <section className="print-hero wrap"><div><img src="/modern-printing.jpg" alt="Preparación de documentos en una impresora multifunción moderna"/><small>Fotografía: George Milton / Pexels</small></div><div><span className="kicker">Servicio completo</span><h2>Imprima lo que necesita, como lo necesita.</h2><p>Desde unas pocas páginas hasta una tesis de grado: confirme formato, cantidad, encuadernación y terminación antes de comenzar.</p><a className="button primary" href="mailto:osmcfg1966@gmail.com?subject=Consulta%20de%20impresi%C3%B3n">Consultar un trabajo →</a></div></section>
  <section className="section wrap print-services">
    <article><ServiceIcon n="01"/><h2>Color y blanco y negro</h2><p>Impresión de documentos con equipos modernos según el propósito de cada trabajo.</p><ul><li>Documentos personales</li><li>Informes y materiales</li><li>Formularios</li><li>Archivos digitales</li></ul></article>
    <article><ServiceIcon n="02"/><h2>Fotocopias</h2><p>Reproducción de documentos para trámites, estudio, archivo o entrega.</p><ul><li>Copias de documentos</li><li>Juegos de páginas</li><li>Material de estudio</li><li>Documentación de apoyo</li></ul></article>
    <article><ServiceIcon n="03"/><h2>Tesis de grado</h2><p>Impresión de tesis y trabajos extensos, cuidando orden, legibilidad y secuencia.</p><ul><li>Portada e interiores</li><li>Gráficos a color</li><li>Texto en blanco y negro</li><li>Copias para entrega</li></ul></article>
    <article><ServiceIcon n="04"/><h2>Encuadernación</h2><p>Organización y terminación de documentos para una entrega profesional y duradera.</p><ul><li>Tesis</li><li>Informes</li><li>Expedientes</li><li>Trabajos académicos</li></ul></article>
    <article><ServiceIcon n="05"/><h2>Plastificado</h2><p>Protección de carnés, identificaciones y documentos hasta tamaño Carta (8½ × 11 pulgadas).</p><ul><li>Carnés personales</li><li>Identificaciones</li><li>Credenciales</li><li>Documentos Carta</li></ul></article>
    <article><ServiceIcon n="06"/><h2>Fotografías</h2><p>Consulte la impresión de fotografías. Si no puede realizarse directamente, Osmany puede referirle otro proveedor.</p><ul><li>Consulta previa</li><li>Tamaños disponibles</li><li>Preparación del archivo</li><li>Referencia responsable</li></ul></article>
  </section>
  <section className="print-details"><div className="wrap"><div className="section-head"><div><span className="kicker light">Más que imprimir</span><h2>Preparación antes de tocar el papel.</h2></div><p>Una buena impresión comienza comprobando el archivo. Osmany puede ayudarle a identificar detalles que conviene corregir o confirmar antes de producir las copias.</p></div><div className="info-card-grid dark-grid"><article><h3>Archivos digitales</h3><p>Puede consultar la impresión desde documentos digitales. Antes de comenzar se revisan la orientación, el tamaño, el orden de las páginas y si el archivo está listo para conservar su apariencia.</p><p>Si necesita una versión editable o cambios de formato, indíquelo antes de imprimir para valorar ese trabajo por separado.</p></article><article><h3>Color o blanco y negro</h3><p>El blanco y negro resulta práctico para textos, copias de consulta y documentación. El color puede ser importante para gráficos, fotografías, portadas, certificados y elementos que deben distinguirse visualmente.</p><p>Es posible combinar interiores en blanco y negro con páginas específicas a color cuando el documento lo permita.</p></article><article><h3>Tesis y trabajos extensos</h3><p>En documentos largos se comprueban portada, índices, numeración, secuencia y páginas especiales. Conviene entregar el archivo final y aprobado para evitar repetir una impresión completa.</p><p>Indique cuántos ejemplares necesita y si todos llevarán la misma encuadernación o terminación.</p></article><article><h3>Documentos para trámites</h3><p>Para copias de identificación, expedientes o formularios, confirme que todas las caras y páginas necesarias estén incluidas y sean legibles.</p><p>Osmany puede ayudar con la preparación material, pero el cliente debe verificar los requisitos de la institución que recibirá el documento.</p></article></div></div></section>
  <section className="print-guide"><div className="wrap"><div><span className="kicker light">Antes de imprimir</span><h2>Traiga el archivo correcto.</h2></div><ol><li><b>Revise el contenido</b><span>Nombres, fechas, páginas y ortografía.</span></li><li><b>Indique el acabado</b><span>Color, cantidad, tamaño y encuadernación.</span></li><li><b>Confirme la entrega</b><span>Especialmente para tesis y trabajos extensos.</span></li></ol></div></section>
  <section className="section wrap print-checklist"><div className="section-head"><div><span className="kicker">Al solicitar el servicio</span><h2>Información que agiliza su pedido.</h2></div><p>Puede enviar estos datos en el primer mensaje para recibir una respuesta más precisa.</p></div><div className="faq-grid"><article><h3>¿Qué va a imprimir?</h3><p>Indique si es un documento, formulario, tesis, fotografía, identificación u otro material.</p></article><article><h3>¿Cuántas páginas y copias?</h3><p>Informe el número aproximado de páginas y cuántos ejemplares completos necesita.</p></article><article><h3>¿Cómo debe quedar?</h3><p>Especifique color o blanco y negro, tamaño, impresión por una o ambas caras y terminación deseada.</p></article><article><h3>¿Para cuándo lo necesita?</h3><p>Comunique la fecha y hora de entrega deseadas para confirmar disponibilidad y plazo.</p></article></div></section>
  <section className="mini-cta"><div className="wrap"><h2>¿Tiene un documento para imprimir?</h2><p>Cuente cuántas páginas necesita y cómo desea recibirlo.</p><Link className="button cream" href="/contacto">Contactar a Osmany →</Link></div></section>
</Shell>}
