import Link from "next/link";
import {PageHero,Shell} from "../site";

const servicios=[
  ["01","Mecanografía y preparación de documentos","Convierte manuscritos, borradores y textos impresos en documentos digitales claros y ordenados. Puede organizar títulos, párrafos, tablas, numeración y otros detalles de presentación para que el contenido resulte fácil de leer, imprimir o compartir.","Es útil para cartas, informes, trabajos académicos, tesis, currículos, documentos personales y materiales de oficina. Antes de terminar, se acuerdan el formato y el tipo de archivo que necesita el cliente."],
  ["02","Impresión y fotocopiado","Imprime documentos a color o en blanco y negro, desde archivos digitales preparados por el cliente o elaborados como parte del servicio. También realiza fotocopias para trámites, estudios, gestiones personales y necesidades de oficina.","La cantidad, el tamaño del papel, el uso de color y la fecha de entrega se confirman antes de comenzar. Para tesis o documentos extensos, también puede coordinarse la organización y terminación del material."],
  ["03","Digitalización de documentos","Transforma documentos en papel en archivos digitales que pueden conservarse, enviarse por correo o volver a imprimirse. Las páginas pueden organizarse en el orden correcto y reunirse en un archivo de varias páginas.","Este servicio ayuda a preservar documentos importantes, reducir el manejo de originales y disponer de copias digitales. La calidad final depende del estado, la legibilidad y el tamaño del material original."],
  ["04","Plastificado y encuadernación","Protege carnés, identificaciones y documentos mediante plastificado, disponible hasta tamaño Carta. Para trabajos de varias páginas, la encuadernación ayuda a mantener el material organizado, protegido y listo para presentar.","Osmany revisa el tamaño, la cantidad de hojas y la terminación necesaria para recomendar una opción adecuada. El precio se confirma según los materiales y el acabado solicitado."],
  ["05","Modelos y formularios de oficina","Diseña modelos reutilizables para oficinas y pequeños negocios, como formularios, listados, controles, hojas de registro, recibos, comunicaciones y otros documentos de uso frecuente.","Cada modelo se adapta a la información que necesita registrar el cliente y a la manera en que será utilizado. El resultado puede quedar preparado para imprimir, completar manualmente o reutilizar en formato digital."],
  ["06","Formularios y orientación migratoria","Ayuda a organizar información y llenar formularios para trámites, incluida la visa de turismo a México y la Ley 20/2022 de España, conocida como Ley de Memoria Democrática o Ley de Nietos.","El cliente debe aportar información verdadera, vigente y los documentos requeridos por la autoridad correspondiente. El servicio facilita la preparación, pero no constituye representación legal ni garantiza la aprobación del trámite."]
];

export default function Sobre(){return <Shell>
  <PageHero kicker="Sobre Osmany" title="Un oficio hecho de atención."><p>Más de quince años de servicio personal, profesionalidad y calidad desde Cienfuegos.</p></PageHero>
  <section className="section wrap story"><div className="story-mark">2010<span>CIENFUEGOS</span></div><div><span className="kicker">Trayectoria</span><h2>Osmany Mecanografía</h2><p className="large">Emprendimiento creado en noviembre de 2010 y consolidado gracias a la preferencia de clientes que valoran la seriedad, el trato personal y la calidad del trabajo.</p><p>Osmany figura profesionalmente como dueño del emprendimiento, mecanógrafo y asesor en temas migratorios. Su actividad comprende impresión, fotocopiado, digitalización, encuadernación y plastificado de documentos hasta tamaño Carta.</p><div className="facts"><div><b>2010</b><span>Año de fundación</span></div><div><b>15+ años</b><span>De experiencia</span></div><div><b>Cienfuegos</b><span>Base profesional</span></div></div><Link className="text-link" href="/cienfuegos">Conozca su orgullo cienfueguero →</Link></div></section>
  <section className="about-services"><div className="wrap"><div className="section-head"><div><span className="kicker light">Qué puede hacer por usted</span><h2>Servicios explicados con claridad.</h2></div><p>Desde preparar una página hasta organizar un trabajo completo, cada solicitud se revisa personalmente para definir el resultado, el plazo y la tarifa antes de comenzar.</p></div><div className="about-service-grid">{servicios.map(servicio=><article key={servicio[0]}><span>{servicio[0]}</span><h3>{servicio[1]}</h3><p>{servicio[2]}</p><p>{servicio[3]}</p></article>)}</div><div className="about-service-actions"><Link className="button primary" href="/servicios">Ver todos los servicios →</Link><Link className="button primary" href="/contacto">Consultar una necesidad →</Link></div></div></section>
  <section className="process"><div className="wrap process-inner"><div><span className="kicker light">Experiencia</span><h2>Servicios que han crecido con sus clientes.</h2></div><ol><li><span>01</span><div><b>Mecanógrafo</b><p>Osmany Mecanografía · desde diciembre de 2010</p></div></li><li><span>02</span><div><b>Dueño del emprendimiento</b><p>Impresión, copias, digitalización, encuadernación y plastificado.</p></div></li><li><span>03</span><div><b>Asesor en temas migratorios</b><p>Visa de turismo a México y Ley 20/2022 de España (LMD o Ley de Nietos).</p></div></li></ol></div></section>
  <section className="sources wrap"><span className="kicker">Fuentes públicas</span><h2>Información profesional</h2><div className="source-grid"><a href="https://www.linkedin.com/in/osmany-santos-mac%C3%ADas-a66106105/"><b>Perfil de LinkedIn</b><span>Experiencia y descripción del emprendimiento ↗</span></a><a href="https://www.todosbiz.com/en-CU/servicio-de-mecanograf-u-eda-a-m-u-e-043-524229"><b>Directorio del negocio</b><span>Ubicación y datos públicos ↗</span></a></div><aside className="migration-note"><span>Información importante</span><h3>Asesoría migratoria con alcance acordado.</h3><p>La asesoría migratoria se ofrece según la necesidad confirmada con Osmany. No implica representación legal ni garantiza la aprobación de visas, ciudadanía u otros trámites.</p></aside></section>
</Shell>}
