import Link from "next/link";
import {PageHero,Shell} from "../site";

export default function Sobre(){return <Shell>
  <PageHero kicker="Sobre Osmany" title="Un oficio hecho de atención."><p>Más de quince años de servicio personal, profesionalidad y calidad desde Cienfuegos.</p></PageHero>
  <section className="section wrap story"><div className="story-mark">2010<span>CIENFUEGOS</span></div><div><span className="kicker">Trayectoria</span><h2>Osmany Mecanografía</h2><p className="large">Emprendimiento creado en noviembre de 2010 y consolidado gracias a la preferencia de clientes que valoran la seriedad, el trato personal y la calidad del trabajo.</p><p>Osmany figura profesionalmente como dueño del emprendimiento, mecanógrafo y asesor en temas migratorios. Su actividad comprende impresión, fotocopiado, digitalización, encuadernación y plastificado de documentos hasta tamaño Carta.</p><div className="facts"><div><b>2010</b><span>Año de fundación</span></div><div><b>15+ años</b><span>De experiencia</span></div><div><b>Cienfuegos</b><span>Base profesional</span></div></div><Link className="text-link" href="/cienfuegos">Conozca su orgullo cienfueguero →</Link></div></section>
  <section className="process"><div className="wrap process-inner"><div><span className="kicker light">Experiencia</span><h2>Servicios que han crecido con sus clientes.</h2></div><ol><li><span>01</span><div><b>Mecanógrafo</b><p>Osmany Mecanografía · desde diciembre de 2010</p></div></li><li><span>02</span><div><b>Dueño del emprendimiento</b><p>Impresión, copias, digitalización, encuadernación y plastificado.</p></div></li><li><span>03</span><div><b>Asesor en temas migratorios</b><p>Visa de turismo a México y Ley 20/2022 de España (LMD o Ley de Nietos).</p></div></li></ol></div></section>
  <section className="sources wrap"><span className="kicker">Fuentes públicas</span><h2>Información profesional</h2><div className="source-grid"><a href="https://www.linkedin.com/in/osmany-santos-mac%C3%ADas-a66106105/"><b>Perfil de LinkedIn</b><span>Experiencia y descripción del emprendimiento ↗</span></a><a href="https://www.todosbiz.com/en-CU/servicio-de-mecanograf-u-eda-a-m-u-e-043-524229"><b>Directorio del negocio</b><span>Ubicación y datos públicos ↗</span></a></div><aside className="migration-note"><span>Información importante</span><h3>Asesoría migratoria con alcance acordado.</h3><p>La asesoría migratoria se ofrece según la necesidad confirmada con Osmany. No implica representación legal ni garantiza la aprobación de visas, ciudadanía u otros trámites.</p></aside></section>
</Shell>}
