import Link from "next/link";
import {PageHero,PagePhoto,ServiceIcon,Shell} from "../site";

const extras=[
  {n:"01",title:"Rescate de fotografías",paragraphs:["Las fotografías antiguas pueden presentar manchas, pérdida de contraste, rayones, dobleces o zonas desvanecidas. Osmany puede preparar una versión digital mejorada, limpiando visualmente el deterioro y ajustando luz, contraste y definición cuando el original lo permita.","Las imágenes en blanco y negro también pueden convertirse a color como una interpretación visual. El resultado depende del tamaño, la nitidez y el estado de la fotografía; por eso se revisa primero el original y se confirma qué mejoras son razonables."],points:["Limpieza y mejora visual","Ajuste de contraste y claridad","Colorización de blanco y negro","Archivo digital para conservar"]},
  {n:"02",title:"Manuscritos a formato digital",paragraphs:["Cartas, libretas, apuntes, recetas, memorias familiares y documentos escritos a mano pueden transcribirse a un archivo digital ordenado. Se conserva el contenido y se organiza con títulos, párrafos, fechas y páginas para facilitar su lectura.","Cuando una palabra resulta difícil de interpretar, se consulta al cliente o se marca la duda en lugar de inventar información. El archivo puede prepararse para conservar, editar, compartir o imprimir según lo acordado."],points:["Cartas y cuadernos","Notas y documentos familiares","Organización por páginas","Entrega editable o lista para imprimir"]},
  {n:"03",title:"Formularios para trámites",paragraphs:["Osmany ayuda a completar formularios de emigración, visa de turismo a México, ciudadanía española mediante la Ley de Memoria Democrática y otros trámites personales. También puede organizar la información necesaria para evitar campos vacíos o datos colocados en secciones incorrectas.","El cliente debe proporcionar información verdadera, vigente y completa, además de revisar el formulario antes de presentarlo. El servicio facilita la preparación documental, pero no sustituye asesoría legal ni garantiza decisiones de consulados, registros u otras autoridades."],points:["Formularios migratorios","Visa de turismo a México","Ley de Memoria Democrática","Otros formularios personales"]},
  {n:"04",title:"Digitalización de documentos",paragraphs:["Los documentos físicos pueden convertirse en archivos digitales para conservarlos, enviarlos por correo, almacenarlos o volver a imprimirlos. Las páginas pueden organizarse en el orden correcto y reunirse en un solo documento cuando sea conveniente.","Antes de comenzar se revisan la cantidad, el tamaño, el estado y la legibilidad de los originales. También puede acordarse una forma clara de nombrar los archivos para localizar cada documento con facilidad."],points:["Documentos de varias páginas","Organización y orden","Archivos para enviar o archivar","Preparación para reimpresión"]},
  {n:"05",title:"Modelos para oficinas",paragraphs:["Se diseñan modelos y plantillas para tareas habituales de oficinas, pequeños negocios y trabajadores por cuenta propia. Pueden incluir hojas de registro, controles, recibos, listados, formularios internos, comunicaciones y documentos repetitivos.","Cada modelo se adapta a los datos que deben registrarse y a la forma en que será utilizado. Puede prepararse para completar a mano, imprimir varias veces o reutilizar digitalmente, con campos claros y una presentación organizada."],points:["Registros y controles","Recibos y listados","Formularios internos","Plantillas reutilizables"]},
  {n:"06",title:"Impresión de fotografías",paragraphs:["Puede consultar la preparación e impresión de fotografías personales, familiares o restauradas. Antes de imprimir se revisan la orientación, el recorte, el tamaño deseado y si el archivo tiene suficiente calidad para el resultado solicitado.","La disponibilidad depende del tamaño, los materiales y el tipo de impresión. Si Osmany no puede realizar el trabajo directamente, le indicará con transparencia y podrá referirle a otro proveedor que atienda esa necesidad."],points:["Revisión de resolución","Tamaño y orientación","Preparación del archivo","Referencia a otro proveedor"]},
  {n:"07",title:"Traducciones limitadas",paragraphs:["Podemos ayudar con traducciones sencillas a distintos idiomas cuando el contenido, la extensión y el propósito estén dentro de nuestras posibilidades. El trabajo puede incluir cartas, comunicaciones, descripciones, mensajes y documentos informativos de complejidad moderada.","Antes de aceptar se revisa el idioma, la cantidad de páginas y el nivel de especialización. No sustituye una traducción jurada, certificada, médica, técnica o legal cuando la institución receptora exige un profesional acreditado."],points:["Textos y comunicaciones sencillas","Varios idiomas según disponibilidad","Preparación bilingüe","Referencia profesional cuando corresponda"]},
  {n:"08",title:"Diseño de sitios web",paragraphs:["¿Desea tener un sitio web como este? Cuéntenos su idea, sus servicios y el público que desea alcanzar. Podemos organizar el contenido y crear una presencia web sencilla, clara y adaptada a teléfonos y computadoras.","El servicio se ofrece de forma limitada y dentro de nuestras posibilidades. Antes de comenzar definimos las páginas, fotografías, textos, formas de contacto, plazo, publicación y mantenimiento que necesita."],points:["Sitios para pequeños negocios","Páginas de servicios y contacto","Diseño adaptable a móviles","Alcance acordado previamente"]},
  {n:"09",title:"Promociones de productos y servicios",paragraphs:["Si no necesita un sitio completo, puede enviarnos fotografías e información para preparar un ejemplo de publicación promocional. Organizamos el nombre, la oferta, el precio, la ubicación y los medios de contacto para que el mensaje sea fácil de entender.","También puede indicarnos dónde desea compartirlo y cómo prefiere pagar el trabajo. Las promociones pueden actualizarse con nuevas ofertas, horarios, imágenes o formas de contacto cuando sea necesario."],points:["Anuncios promocionales","Fichas de productos y servicios","Organización de fotos e información","Actualizaciones de ofertas"]},
  {n:"10",title:"Búsqueda de otros proveedores",paragraphs:["¿No encuentra aquí el servicio de oficina que necesita? Explíquenos su idea. Revisaremos si podemos realizarla directamente o si requiere herramientas, conocimientos o autorizaciones diferentes.","Cuando el trabajo esté fuera de nuestro alcance, procuraremos orientarle hacia otro proveedor. La contratación, condiciones, calidad y pago del servicio referido se acuerdan directamente con ese proveedor."],points:["Consulta abierta de necesidades","Valoración inicial","Orientación práctica","Contacto con otros proveedores"]}
];

export default function OtrosServicios(){return <Shell>
  <PageHero kicker="Otros servicios" title="Conservar, completar y resolver."><p>Apoyo práctico para recuperar recuerdos, preservar documentos y preparar materiales personales o profesionales con atención a cada detalle.</p></PageHero>
  <PagePhoto src="/writing-desk.jpg" alt="Detalle de escritura sobre un documento en papel" label="Del papel al archivo" caption="Lo importante puede conservarse y volver a utilizarse." credit="Fotografía de archivo · Unsplash"/>
  <section className="section wrap extra-services"><div className="section-head"><div><span className="kicker">Soluciones adicionales</span><h2>¿Qué se puede hacer?</h2></div><p>Cada material se revisa antes de confirmar el alcance. Así se determina qué resultado es posible, cuánto tiempo requiere y cómo conviene entregarlo.</p></div><div className="detail-list">{extras.map(extra=><article key={extra.n}><ServiceIcon n={extra.n}/><div><h2>{extra.title}</h2>{extra.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<ul>{extra.points.map(point=><li key={point}>{point}</li>)}</ul></div></article>)}</div></section>
  <section className="extra-request"><div className="wrap"><div className="section-head"><div><span className="kicker light">Para solicitarlo</span><h2>Comparta una muestra clara.</h2></div><p>Una fotografía del original o una breve explicación permite valorar mejor el servicio antes de que tenga que trasladar todo el material.</p></div><div className="info-card-grid dark-grid"><article><h3>1. Explique la necesidad</h3><p>Cuente qué material tiene, qué desea recuperar o preparar y para qué utilizará el resultado.</p></article><article><h3>2. Envíe una muestra</h3><p>Cuando sea posible, comparta una imagen legible de la fotografía, manuscrito, documento o formulario.</p></article><article><h3>3. Confirme el resultado</h3><p>Indique si necesita archivo digital, versión editable, impresión, copias o una terminación específica.</p></article></div></div></section>
  <section className="process"><div className="wrap process-inner"><div><span className="kicker light">Importante</span><h2>Ayuda documental, sin confusión.</h2><p className="process-lead">La información se organiza junto al cliente y se revisa antes de entregar o presentar.</p></div><ol><li><span>1</span><div><b>Usted aporta la información</b><p>Los datos, nombres, fechas y documentos deben ser correctos y completos.</p></div></li><li><span>2</span><div><b>Osmany prepara el material</b><p>Se trabaja según el alcance, formato y resultado confirmados previamente.</p></div></li><li><span>3</span><div><b>Usted realiza la revisión final</b><p>Compruebe datos personales y requisitos antes de presentar un formulario o trámite.</p></div></li><li><span>4</span><div><b>Las autoridades toman la decisión</b><p>La preparación documental no garantiza visas, ciudadanía ni aprobaciones oficiales.</p></div></li></ol></div></section>
  <section className="section wrap extra-faq"><div className="section-head"><div><span className="kicker">Preguntas frecuentes</span><h2>Antes de comenzar.</h2></div><p>Estas aclaraciones ayudan a definir expectativas y proteger los originales.</p></div><div className="faq-grid"><article><h3>¿Se modifica el original?</h3><p>La restauración y digitalización se realizan sobre una copia digital. El original se utiliza como referencia y debe conservarse con cuidado.</p></article><article><h3>¿Toda foto puede colorearse?</h3><p>Puede intentarse cuando existe suficiente detalle, pero los colores son una interpretación y la calidad depende del original.</p></article><article><h3>¿Puedo llevar muchas páginas?</h3><p>Sí. Indique la cantidad aproximada para acordar el orden, el formato, el plazo y la tarifa del trabajo completo.</p></article><article><h3>¿Qué sucede si falta información?</h3><p>Osmany señalará las dudas para que usted pueda completarlas. No se inventan datos en documentos o formularios.</p></article></div></section>
  <section className="mini-cta"><div className="wrap"><h2>¿Necesita uno de estos servicios?</h2><p>Explique el material, envíe una muestra y cuente qué resultado busca.</p><Link className="button cream" href="/contacto">Consultar con Osmany →</Link></div></section>
</Shell>}
