"use client";
import {useState} from "react";

const photos=[
  {src:"/cienfuegos-01.jpg",alt:"Escena urbana de Cienfuegos compartida por Osmany",caption:"Cienfuegos, ciudad de historia, luz y orgullo cotidiano.",credit:"Fotografía pública compartida por Osmany"},
  {src:"/cienfuegos-05.jpg",alt:"Atardecer rosado sobre una calle de Cienfuegos",caption:"Un cielo rosado al caer la tarde en Cienfuegos.",credit:"Fotografía pública compartida por Osmany"},
  {src:"/cienfuegos-08.jpg",alt:"Gran árbol y calle tranquila de Cienfuegos",caption:"La sombra de un gran árbol sobre una mañana tranquila.",credit:"Fotografía pública compartida por Osmany"},
  {src:"/cienfuegos-09.jpg",alt:"Colección de plantas verdes cuidada en un patio cienfueguero",caption:"El verde y el cuidado cotidiano de un patio de la ciudad.",credit:"Fotografía pública compartida por Osmany"},
  {src:"/cienfuegos-02.jpg",alt:"Vida cotidiana en una calle arbolada de Cienfuegos",caption:"Movimiento y vida diaria en las calles cienfuegueras.",credit:"Fotografía pública compartida por Osmany"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/2020-12-30_Cienfuegos_45.jpg/1920px-2020-12-30_Cienfuegos_45.jpg",alt:"Bahía de Cienfuegos",caption:"La serenidad y amplitud de la bahía de Cienfuegos.",credit:"Wikimedia Commons · Burkhard Mücke · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/AJM_077_Bah%C3%ADa_de_Cienfuegos_.JPG/1920px-AJM_077_Bah%C3%ADa_de_Cienfuegos_.JPG",alt:"Vista de la bahía de Cienfuegos",caption:"La bahía vista bajo la luz del Caribe.",credit:"Wikimedia Commons · Arnoud Joris Maaswinkel · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Approaching_Cienfuegos_-_panoramio.jpg/1920px-Approaching_Cienfuegos_-_panoramio.jpg",alt:"Llegada por mar a Cienfuegos",caption:"Una mirada a Cienfuegos desde sus aguas.",credit:"Wikimedia Commons · balepc · CC BY 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Badia_Cienfuegos.JPG/1920px-Badia_Cienfuegos.JPG",alt:"Agua azul en la bahía de Cienfuegos",caption:"Azules tranquilos en la bahía cienfueguera.",credit:"Wikimedia Commons · Mmoyaq · CC BY-SA 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Bahia_de_Cienfuegos_1-2.jpg/1920px-Bahia_de_Cienfuegos_1-2.jpg",alt:"Panorama de la bahía de Cienfuegos",caption:"Horizonte abierto sobre la bahía.",credit:"Wikimedia Commons · Colsu · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Bahia_de_Cienfuegos_1.jpg/1920px-Bahia_de_Cienfuegos_1.jpg",alt:"Costa de la bahía de Cienfuegos",caption:"La costa que acompaña a la Perla del Sur.",credit:"Wikimedia Commons · Colsu · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/5/53/Cienfuegos_%281983%29_03.jpg",alt:"Naturaleza de Cienfuegos",caption:"Naturaleza viva en los alrededores de Cienfuegos.",credit:"Wikimedia Commons · LBM1948 · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/1/17/Cienfuegos_%281983%29_04.jpg",alt:"Paisaje natural de Cienfuegos",caption:"El paisaje natural también cuenta la historia de la ciudad.",credit:"Wikimedia Commons · LBM1948 · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Flamencos%2C_Laguna_de_Guanaroca%2C_Cuba.jpg/1920px-Flamencos%2C_Laguna_de_Guanaroca%2C_Cuba.jpg",alt:"Flamencos en la Laguna de Guanaroca",caption:"Flamencos y calma en la Laguna de Guanaroca.",credit:"Wikimedia Commons · Scmresearcher · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/2012-02_botanic_garden_Cienfuegos_anagoria_01.JPG/1920px-2012-02_botanic_garden_Cienfuegos_anagoria_01.JPG",alt:"Jardín Botánico de Cienfuegos",caption:"El verde tropical del Jardín Botánico.",credit:"Wikimedia Commons · Anagoria · CC BY 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/2012-02_botanic_garden_Cienfuegos_anagoria_02.JPG/1920px-2012-02_botanic_garden_Cienfuegos_anagoria_02.JPG",alt:"Vegetación tropical del Jardín Botánico",caption:"Senderos rodeados de vegetación tropical.",credit:"Wikimedia Commons · Anagoria · CC BY 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/2012-02_botanic_garden_Cienfuegos_anagoria_03.JPG/1920px-2012-02_botanic_garden_Cienfuegos_anagoria_03.JPG",alt:"Palmas del Jardín Botánico de Cienfuegos",caption:"Palmas, sombra y naturaleza cienfueguera.",credit:"Wikimedia Commons · Anagoria · CC BY 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/2012-02_botanic_garden_Cienfuegos_anagoria_05.JPG/1920px-2012-02_botanic_garden_Cienfuegos_anagoria_05.JPG",alt:"Plantas del Jardín Botánico de Cienfuegos",caption:"Una colección viva de colores y formas tropicales.",credit:"Wikimedia Commons · Anagoria · CC BY 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/2012-02_botanic_garden_Cienfuegos_anagoria_06.JPG/1920px-2012-02_botanic_garden_Cienfuegos_anagoria_06.JPG",alt:"Paisaje verde del Jardín Botánico",caption:"La tranquilidad verde del Jardín Botánico.",credit:"Wikimedia Commons · Anagoria · CC BY 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/2012-02_botanic_garden_Cienfuegos_anagoria_07.JPG/1920px-2012-02_botanic_garden_Cienfuegos_anagoria_07.JPG",alt:"Naturaleza tropical en Cienfuegos",caption:"Naturaleza tropical para caminar sin prisa.",credit:"Wikimedia Commons · Anagoria · CC BY 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Leiocephalus_carinatus_sur_une_terrasse_-_playa_Rancho_Luna.jpg/1920px-Leiocephalus_carinatus_sur_une_terrasse_-_playa_Rancho_Luna.jpg",alt:"Fauna de Playa Rancho Luna",caption:"Pequeños habitantes junto al mar de Rancho Luna.",credit:"Wikimedia Commons · Patrice78500 · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Playa_Rancho_Luna_-_parasol.jpg/1920px-Playa_Rancho_Luna_-_parasol.jpg",alt:"Sombrilla frente al mar en Playa Rancho Luna",caption:"Un rincón para descansar frente al Caribe.",credit:"Wikimedia Commons · Patrice78500 · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Playa_Rancho_Luna_Cienfuegos_Cuba.jpg/1920px-Playa_Rancho_Luna_Cienfuegos_Cuba.jpg",alt:"Playa Rancho Luna en Cienfuegos",caption:"El agua clara de Playa Rancho Luna.",credit:"Wikimedia Commons · Jan Pešula · CC0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Playa_Rancho_Luna.jpg/1920px-Playa_Rancho_Luna.jpg",alt:"Costa de Playa Rancho Luna",caption:"Mar y descanso muy cerca de Cienfuegos.",credit:"Wikimedia Commons · Patrice78500 · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/a/a0/Rancho_luna%2C_Cienfuegos%2C_Cuba.jpg",alt:"Paisaje costero de Rancho Luna",caption:"La costa de Rancho Luna bajo el sol cubano.",credit:"Wikimedia Commons · Apbravo · CC BY-SA 4.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Bl%C3%A9ck_iwwer_Cienfuegos.JPG/1920px-Bl%C3%A9ck_iwwer_Cienfuegos.JPG",alt:"Vista panorámica de Cienfuegos",caption:"Una vista abierta de la Perla del Sur.",credit:"Wikimedia Commons · Alexandra · CC BY-SA 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Cienfuegos_from_above_-_2019.jpg/1920px-Cienfuegos_from_above_-_2019.jpg",alt:"Cienfuegos vista desde el aire",caption:"La ciudad y la bahía vistas desde lo alto.",credit:"Wikimedia Commons · Payton Chung · CC BY 2.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Cienfuegos_panorama_from_bay.jpg/1920px-Cienfuegos_panorama_from_bay.jpg",alt:"Panorama de Cienfuegos desde la bahía",caption:"Cienfuegos se abre frente a su bahía.",credit:"Wikimedia Commons · Jan Pešula · CC0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Cienfuegos_street_panorama.jpg/1920px-Cienfuegos_street_panorama.jpg",alt:"Panorama de una calle de Cienfuegos",caption:"La amplitud de sus calles y su vida cotidiana.",credit:"Wikimedia Commons · Anton Zelenov · CC BY-SA 3.0"},
  {src:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Cienfuegos_tower.jpg/1920px-Cienfuegos_tower.jpg",alt:"Cienfuegos vista desde una torre",caption:"Otra perspectiva sobre la ciudad y su horizonte.",credit:"Wikimedia Commons · Anton Zelenov · CC BY 3.0"},
];

export default function CityCarousel(){const [active,setActive]=useState(0);const move=(step:number)=>setActive((active+step+photos.length)%photos.length);return <section className="city-carousel wrap" aria-label="Galería fotográfica de Cienfuegos" onKeyDown={e=>{if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)}} tabIndex={0}><div className="city-slide"><img src={photos[active].src} alt={photos[active].alt}/><div className="city-slide-copy"><span>{String(active+1).padStart(2,"0")} / {String(photos.length).padStart(2,"0")}</span><b>{photos[active].caption}</b><small>{photos[active].credit}</small></div></div><div className="city-controls"><button type="button" onClick={()=>move(-1)} aria-label="Foto anterior">← Anterior</button><div>{photos.map((photo,index)=><button type="button" className={index===active?"active":""} onClick={()=>setActive(index)} aria-label={`Ver foto ${index+1}`} key={photo.src}/>)}</div><button type="button" onClick={()=>move(1)} aria-label="Foto siguiente">Siguiente →</button></div></section>}
