import {PageHero,PagePhoto,Shell} from "../site";

const steps=[
  {n:"01",title:"Comparta el material",paragraphs:["El trabajo puede comenzar con manuscritos, hojas impresas, fotografías, notas, formularios o archivos digitales. Envíe o lleve el material más completo y legible que tenga, incluyendo anexos y páginas de referencia.","Explique para qué se utilizará el resultado: un trámite, una entrega académica, un archivo personal, una oficina o una impresión. Si debe respetarse un modelo, una plantilla o instrucciones específicas, conviene compartirlos desde el principio."],points:["Tipo y estado del original","Uso final del trabajo","Modelo o instrucciones disponibles"]},
  {n:"02",title:"Definimos el resultado",paragraphs:["Osmany revisa lo recibido y conversa con usted para entender exactamente qué necesita. Se determina si el encargo incluye mecanografía, digitalización, corrección de formato, impresión, copias, plastificado, encuadernación o llenado de formularios.","También se confirman la cantidad de páginas o ejemplares, el tamaño, el uso de color, el formato del archivo y la fecha deseada. Con esa información se comunica el alcance, el plazo estimado, la forma de pago y la tarifa antes de comenzar."],points:["Servicio y cantidad","Formato y terminación","Plazo, precio y pago"]},
  {n:"03",title:"Preparación cuidadosa",paragraphs:["El contenido se mecanografía, escanea, organiza o completa según el servicio acordado. Se presta atención especial a nombres propios, números, fechas, direcciones y otros datos que no deben interpretarse de manera incorrecta.","Cuando una palabra no es legible o falta información, Osmany consulta al cliente en lugar de asumir. Los documentos se manejan con discreción y únicamente para realizar el trabajo solicitado."],points:["Datos escritos con precisión","Consulta ante dudas","Manejo discreto del material"]},
  {n:"04",title:"Orden y presentación",paragraphs:["Una vez preparado el contenido, se organiza para que resulte claro y apropiado para su propósito. Pueden ajustarse márgenes, espaciado, títulos, alineación, tablas, numeración y paginación.","Si el documento será impreso, también se comprueban el tamaño de la hoja, la orientación y la distribución de los elementos. Para modelos de oficina, se procura que los campos sean fáciles de completar y reutilizar."],points:["Lectura clara y ordenada","Formato adecuado para imprimir","Presentación adaptada al uso"]},
  {n:"05",title:"Comprobación final",paragraphs:["Antes de entregar, se revisa que las páginas estén completas y en el orden correcto. También se comprueban la legibilidad, la consistencia visual y los detalles acordados para impresión o terminación.","El cliente conserva la responsabilidad de verificar datos personales, nombres, fechas y requisitos oficiales. Si durante la revisión aparece una duda importante, se consulta antes de producir copias, plastificar o encuadernar."],points:["Páginas completas y ordenadas","Consistencia del formato","Confirmación de datos importantes"]},
  {n:"06",title:"Entrega acordada",paragraphs:["El trabajo se entrega en el formato confirmado: archivo digital, documento impreso, fotocopias, material encuadernado o plastificado. Se verifica la cantidad y la terminación antes de cerrar el encargo.","Si el cliente necesita conservar una versión editable, imprimir más ejemplares o realizar una actualización posterior, puede indicarlo. La entrega se coordina directamente con Osmany según el tipo de trabajo y las condiciones acordadas."],points:["Archivo o material terminado","Cantidad comprobada","Orientación para copias futuras"]}
];

export default function Proceso(){return <Shell>
  <PageHero kicker="Cómo trabajo" title="Claro desde el primer contacto."><p>Un proceso sencillo para entender el encargo, confirmar cada detalle y entregar un resultado preparado para su propósito.</p></PageHero>
  <PagePhoto src="/writing-desk.jpg" alt="Detalle de escritura y revisión de un documento" label="Atención al original" caption="Cada dato cuenta antes de comenzar." credit="Fotografía de archivo · Unsplash"/>
  <section className="section wrap process-guide"><div className="section-head"><div><span className="kicker">Paso a paso</span><h2>Siempre sabrá qué sigue.</h2></div><p>El alcance y la duración pueden variar según el encargo, pero la comunicación, la confirmación previa y el cuidado de los detalles se mantienen en cada trabajo.</p></div><div className="timeline">{steps.map(step=><article key={step.n}><span>{step.n}</span><div><h2>{step.title}</h2>{step.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}<ul>{step.points.map(point=><li key={point}>{point}</li>)}</ul></div></article>)}</div></section>
  <section className="process"><div className="wrap process-inner"><div><span className="kicker light">Antes de empezar</span><h2>Lo que conviene traer.</h2><p className="process-lead">Cuanta más información comparta al inicio, más precisa será la cotización y más sencillo resultará completar el trabajo.</p></div><ol><li><span>✓</span><div><b>El material más completo posible</b><p>Incluya anexos, nombres correctos, páginas de referencia y cualquier documento relacionado.</p></div></li><li><span>✓</span><div><b>Una muestra o instrucción</b><p>Si debe seguir una plantilla, formato institucional o ejemplo anterior, llévelo consigo.</p></div></li><li><span>✓</span><div><b>Fecha y uso final</b><p>Indique cuándo lo necesita, cuántos ejemplares requiere y ante quién será presentado.</p></div></li><li><span>✓</span><div><b>Datos para aclarar dudas</b><p>Deje una vía de contacto disponible por si surge una palabra ilegible o un dato incompleto.</p></div></li></ol></div></section>
  <section className="mini-cta"><div className="wrap"><h2>¿Listo para comenzar?</h2><p>Explique qué necesita, comparta una muestra y reciba una confirmación antes de empezar.</p><a className="button cream" href="mailto:osmcfg1966@gmail.com">Consultar disponibilidad →</a></div></section>
</Shell>}
