import Link from "next/link";
import {PageHero,Shell} from "../site";

const resources=[
  ["01","Papel","Resmas y tamaños necesarios para imprimir documentos, formularios, trabajos académicos y copias."],
  ["02","Tinta","Tinta y cartuchos para mantener disponibles las impresiones a color y en blanco y negro."],
  ["03","Impresoras","Compra, reparación y mantenimiento de impresoras, computadoras y equipos de trabajo."],
  ["04","Baterías de respaldo","Baterías y soluciones de energía que permitan continuar durante los cortes eléctricos."]
];

export default function Donaciones(){return <Shell>
  <PageHero kicker="Contribución voluntaria" title="Ayúdanos a mantener el servicio."><p>Nuestro pequeño negocio trabaja para ofrecer mecanografía, impresión y digitalización útiles y accesibles en Cienfuegos. Su apoyo monetario ayuda a enfrentar el alto costo y la escasez de materiales y equipos.</p></PageHero>

  <section className="donation-intro wrap"><figure><img src="/osmany-mecanografia-promo.png" alt="Osmany Santos Macías y la presentación de su servicio de mecanografía"/><figcaption>Un emprendimiento cienfueguero en servicio desde 2010.</figcaption></figure><div><span className="kicker">Por qué pedimos apoyo</span><h2>Continuar trabajando, incluso en momentos difíciles.</h2><p>El papel, la tinta, las piezas de repuesto y los equipos necesarios tienen costos elevados y no siempre están disponibles. Los apagones también hacen necesario contar con baterías y sistemas de respaldo de energía.</p><p>Las contribuciones se reciben únicamente en dinero y se destinan a recursos relacionados directamente con la continuidad del servicio.</p><div className="donation-goal"><small>Meta inicial propuesta</small><strong>US$300</strong><span>Para apoyar la compra de una impresora y una batería de respaldo.</span></div></div></section>

  <section className="donation-use"><div className="wrap"><div className="section-head"><div><span className="kicker light">Uso de los aportes</span><h2>¿En qué se utilizará el dinero?</h2></div><p>El objetivo es fortalecer los recursos esenciales para mecanografiar, imprimir, copiar y digitalizar documentos.</p></div><div className="donation-resource-grid">{resources.map(resource=><article key={resource[0]}><span>{resource[0]}</span><h3>{resource[1]}</h3><p>{resource[2]}</p></article>)}</div></div></section>

  <section className="section wrap paypal-support"><div className="paypal-copy"><span className="kicker">Tu ayuda hace la diferencia</span><h2>Apoya mediante PayPal.</h2><p>Cada aporte, sin importar su tamaño, ayuda a mantener los equipos funcionando y a continuar atendiendo a la comunidad.</p><ol><li>Abra la cámara de su teléfono o la aplicación de PayPal.</li><li>Escanee el código QR.</li><li>Elija en PayPal la cantidad que desea aportar y confirme los datos antes de enviar.</li></ol><p className="paypal-safety"><strong>Pago protegido fuera de este sitio.</strong> Esta página no solicita ni almacena números de tarjeta, claves, correos de acceso ni información bancaria.</p></div><figure className="paypal-qr"><img src="/paypal-apoyo-qr.png" alt="Código QR de PayPal para realizar una contribución voluntaria"/><figcaption>Escanee con la cámara de su teléfono para abrir PayPal.</figcaption></figure></section>

  <section className="section wrap transparency"><div className="section-head"><div><span className="kicker">Transparencia</span><h2>Un compromiso claro con cada aporte.</h2></div><p>Los ingresos y las comisiones del procesador deben registrarse en la contabilidad del negocio y clasificarse con orientación profesional cuando corresponda.</p></div><div className="transparency-grid"><article><h3>Uso relacionado con el servicio</h3><p>Los fondos se aplicarán a papel, tinta, impresoras, reparaciones, mantenimiento, baterías y otras soluciones necesarias para continuar trabajando.</p></article><article><h3>Actualizaciones</h3><p>Se compartirán noticias sobre compras y mejoras importantes realizadas gracias a las contribuciones recibidas.</p></article><article><h3>Sin ventajas especiales</h3><p>Contribuir no genera prioridad, descuentos, servicios gratuitos ni beneficios especiales. Los trabajos contratados se cotizan y pagan por separado.</p></article></div><aside className="donation-legal"><strong>Aviso importante</strong><p>Este es un aporte monetario voluntario para apoyar un pequeño negocio privado. No constituye una donación benéfica deducible de impuestos y no se emitirá un recibo fiscal oficial. El aporte no sustituye el pago de ningún servicio contratado.</p></aside></section>

  <section className="mini-cta"><div className="wrap"><h2>Gracias por apoyar nuestro trabajo.</h2><p>Su contribución nos ayuda a seguir preparando, imprimiendo y digitalizando documentos para nuestra comunidad.</p><Link className="button cream" href="/contacto">Consultar cómo apoyar →</Link></div></section>
</Shell>}
